# Generated by Django 4.2.13 on 2025-04-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("customer_unique_id", models.UUIDField()),
                ("state_code", models.CharField(max_length=250)),
                ("city_id", models.IntegerField()),
                ("orders_total", models.IntegerField()),
                ("last_activity", models.DateField()),
                ("avg_delivery_distance_km", models.FloatField()),
                ("min_delivery_distance_km", models.FloatField()),
                ("max_delivery_distance_km", models.FloatField()),
                ("avg_expected_delivery_days", models.FloatField()),
                ("avg_actual_delivery_days", models.FloatField()),
                ("avg_delay", models.FloatField()),
                ("avg_delay_factor", models.FloatField()),
                ("avg_delivery_speed", models.FloatField()),
                ("avg_delivery_cost", models.FloatField()),
                ("avg_order_cost", models.FloatField()),
                ("cancelled_ratio", models.FloatField()),
                ("free_delivery_ratio", models.FloatField()),
                ("sale_orders_ratio", models.FloatField()),
                ("home_seller_ratio", models.FloatField()),
                ("favorite_seller_state_code", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name": "Покупатель",
                "verbose_name_plural": "Покупатели",
                "db_table": "analysis_geo_customers",
                "managed": False,
            },
        ),
    ]
