# Generated by Django 4.2.13 on 2025-04-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.UUIDField(primary_key=True, serialize=False)),
                ("product_category_name", models.CharField(max_length=250)),
                ("product_name_lenght", models.IntegerField()),
                ("product_description_lenght", models.IntegerField()),
                ("product_photos_qty", models.IntegerField()),
                ("product_weight_g", models.IntegerField()),
                ("product_length_cm", models.IntegerField()),
                ("product_height_cm", models.IntegerField()),
                ("product_width_cm", models.IntegerField()),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "db_table": "products",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.UUIDField(primary_key=True, serialize=False)),
                ("order_id", models.UUIDField()),
                ("score", models.IntegerField()),
                ("message", models.CharField()),
                ("message_ru", models.CharField()),
                ("creation_date", models.DateField()),
                ("q1", models.BooleanField()),
                ("q2", models.IntegerField()),
                ("q3", models.BooleanField()),
                ("q4", models.BooleanField()),
                ("q5", models.BooleanField()),
                ("q6", models.IntegerField()),
                ("q7", models.BooleanField()),
                ("q8", models.BooleanField()),
                ("q9", models.IntegerField()),
                ("q10", models.BooleanField()),
                ("q11", models.BooleanField()),
                ("customer_unique_id", models.UUIDField()),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "db_table": "analysis_nlp_reviews",
                "managed": False,
            },
        ),
    ]
