# Generated by Django 4.2.13 on 2025-04-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Человекочитаемое название модели",
                        max_length=255,
                        verbose_name="Рабочее название модели",
                    ),
                ),
                (
                    "model_file",
                    models.CharField(
                        help_text="Имя файла с сохраненной моделью (например, model.cbm)",
                        max_length=255,
                        verbose_name="Название файла модели",
                    ),
                ),
                (
                    "mean_values_json",
                    models.JSONField(
                        default=dict,
                        help_text="JSON с средними/медианными значениями для заполнения пропусков",
                        verbose_name="Средние значения для заполнения NA",
                    ),
                ),
                (
                    "metrics_offset_json",
                    models.JSONField(
                        default=dict,
                        help_text="JSON с коэффициентами для балансировки recall/precision",
                        verbose_name="Смещение между recall и precision",
                    ),
                ),
                ("precision_true", models.IntegerField(verbose_name="Precision - да")),
                ("recall_true", models.IntegerField(verbose_name="Recall - да")),
                ("f1_true", models.IntegerField(verbose_name="F1 - да")),
                (
                    "precision_false",
                    models.IntegerField(verbose_name="Precision - нет"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "ML Модель",
                "verbose_name_plural": "ML Модели",
                "ordering": ["-created_at"],
            },
        ),
    ]
