# Generated by Django 4.2.13 on 2025-04-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_mlmodel"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="mlmodel",
            table="api_mlmodel",
        ),
    ]
