# Generated by Django 4.2.13 on 2025-04-20 07:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_mlmodel_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodel",
            name="feature_columns",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Список колонок, которые использовались при обучении",
                size=None,
                verbose_name="Колонки признаков модели",
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="mean_values_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON с средними/медианными значениями для заполнения пропусков",
                verbose_name="Средние значения для заполнения NA",
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="metrics_offset_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON с коэффициентами для балансировки recall/precision",
                verbose_name="Смещение между recall и precision",
            ),
        ),
    ]
