# Generated by Django 4.2.13 on 2025-04-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_mlmodel_feature_columns_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodel",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
