# Generated by Django 4.2.13 on 2025-04-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_mlmodel_is_main"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerFeaturesCurrent",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("order_id", models.UUIDField()),
                ("customer_unique_id", models.UUIDField()),
                ("timeline_date", models.DateField()),
                ("city_size", models.FloatField()),
                ("city_center_distance_km", models.FloatField()),
                ("city_center_level", models.FloatField()),
                ("days_after_order", models.IntegerField()),
                ("state_income", models.IntegerField()),
                ("last_delivery_distance_km", models.IntegerField()),
                ("last_delivery_cost", models.FloatField()),
                ("last_order_cost", models.FloatField()),
                ("last_review_score", models.IntegerField()),
                ("last_review_length", models.IntegerField()),
                ("last_review_product_state", models.IntegerField()),
                ("last_review_sentiment", models.IntegerField()),
                ("avg_order_interval_days", models.IntegerField()),
                ("main_payment_type", models.CharField(max_length=250)),
                ("last_order_day_of_year", models.IntegerField()),
                ("pred_proba", models.FloatField()),
            ],
            options={
                "verbose_name": "Параметр прогнозирования",
                "verbose_name_plural": "Параметры прогнозирования",
                "db_table": "customer_features_current",
                "managed": False,
            },
        ),
    ]
