# Generated by Django 4.2.13 on 2025-04-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_customerfeaturescurrent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAbcAalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_unique_id", models.UUIDField()),
                ("sum", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cumulative_revenue",
                    models.DecimalField(
                        db_column='"Cumulative revenue"',
                        decimal_places=2,
                        max_digits=12,
                    ),
                ),
                (
                    "cumulative_percentage",
                    models.DecimalField(
                        db_column='"Cumulative percentage"',
                        decimal_places=7,
                        max_digits=9,
                    ),
                ),
                ("category", models.CharField(db_column='"Category"', max_length=1)),
            ],
            options={
                "verbose_name": "ABC анализ",
                "verbose_name_plural": "ABC анализы",
                "db_table": "analysis_abc_customer_payment_value",
                "managed": False,
            },
        ),
    ]
